routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::get('/', function () { return view('welcome'); });

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth']], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	// Custom routes for email
	// Route::get('email/verify/{id}/{hash}', 'Auth\VerificationController@verify')->name('verification.verify')->middleware('signed');
	// Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
	// Route::post('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

	Route::get('/change-password', 'Auth\ChangePasswordController@index' )->name('password.index');
	Route::post('/change-password', 'Auth\ChangePasswordController@store' )->name('password.store');

	Route::resources([
	    'acl/roles' => 'Acl\RoleController',
	    'acl/permissions' => 'Acl\PermissionController',
	    'acl/users' => 'Acl\UserController'
	]);
	Route::get('/acl/roles/{id}/permissions', 'Acl\RoleController@showRolePermissions')->name('roles.permissions');
	Route::post('/acl/roles/{roleId}/permissions', 'Acl\RoleController@addingPermissionToRole')->name('roles.permissions.add');
	Route::delete('/acl/roles/{roleId}/permissions', 'Acl\RoleController@removingPermissionFromRole')->name('roles.permissions.remove');

	Route::get('/acl/users/{userId}/roles', 'Acl\UserController@editingRolesUser')->name('users.roles');
	Route::post('/acl/users/{userId}/roles', 'Acl\UserController@addingRoleToUser')->name('users.roles.add');
	Route::delete('/acl/users/{userId}/roles', 'Acl\UserController@removingRoleFromUser')->name('users.roles.remove');

	Route::get('/acl/permissions', 'Acl\PermissionController@index')->name('permissions.index');
	Route::get('/acl/permissions/{id}', 'Acl\PermissionController@show')->name('permissions.show');

	Route::get('/profile', 'ContactController@index')->name('profiles.index');
	Route::patch('/profile', 'ContactController@update')->name('profiles.update');

	// Blog Post
	Route::get('/articles/new', 'PostController@newPost' )->name('blogs.create');
	Route::post('/articles', 'PostController@store' )->name('blogs.store');
	Route::patch('/articles/{id}', 'PostController@update')->name('blogs.update');
	Route::get('/articles/{slug}/edit', ['as' => 'blogs.edit', 'uses' => 'PostController@edit'])->where('slug', '[A-Za-z0-9-_]+');

	// Comments
	Route::post('/comments', 'CommentController@store' )->name('comments.store');
	Route::patch('/comments/{id}/disable', 'CommentController@disableComments' )->name('comments.disable');

	// Bookmarks
	Route::get('/bookmarks', 'BookmarkController@index' )->name('bookmarks');
	Route::get('/bookmarks/new', 'BookmarkController@create' )->name('bookmarks.create');
	Route::post('/bookmarks', 'BookmarkController@store' )->name('bookmarks.store');
	Route::get('/bookmarks/{id}', 'BookmarkController@edit')->name('bookmarks.edit');
	Route::patch('/bookmarks/{id}', 'BookmarkController@update')->name('bookmarks.update');
	Route::delete('/bookmarks/{id}', 'BookmarkController@destroy')->name('bookmarks.delete');
	Route::get('/bookmarks/{id}/download', 'BookmarkController@exportToJSON')->name('bookmarks.download');
	Route::post('/bookmarks/{id}/upload', 'BookmarkController@importJSON')->name('bookmarks.upload');
});

// Blogs public routes
Route::get('/articles/dashboard', 'PostController@index' )->name('blogs');
Route::get('/articles', 'PostController@articleList' )->name('blogs.list');

Route::get('/articles/{slug}', ['as' => 'blogs.show', 'uses' => 'PostController@show'])->where('slug', '[A-Za-z0-9-_]+');

app/Models/Acl/Permission.php
<?php

namespace App\Models\Acl;

use Spatie\Permission\Models\Permission as SpatiePermission;


class Permission extends SpatiePermission
{
    /**
     * Create a new Eloquent model instance.
     *
     * @param  array  $attributes
     * @return void
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->mergeFillable(['color', 'description']);
    }
}

app/Models/Acl/Role.php
<?php

namespace App\Models\Acl;

use Spatie\Permission\Models\Role as SpatieRole;

class Role extends SpatieRole
{
    /**
     * Create a new Eloquent model instance.
     *
     * @param  array  $attributes
     * @return void
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->mergeFillable(['color', 'description']);
    }
}

app/Http/Controllers/Acl/PermissionController.php
<?php

namespace App\Http\Controllers\Acl;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\PermissionRepository ;
use App\Http\Requests\PermissionStoreRequest;

class PermissionController extends Controller
{

    private $permissionRepo;

    public function __construct(PermissionRepository $permissionRepo) 
    {
        $this->permissionRepo = $permissionRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('acl.permissions.list', [
                'permissions' => $this->permissionRepo->getAll()
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('acl.permissions.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionStoreRequest $request)
    {
        $validated = $request->validated();
        
        $isSaved = $this->permissionRepo->save($request);
        
        if ($isSaved) {
            return redirect()->back()->with(['success'=> 'New permissions has been created']);
        }
        return redirect()->back()->with(['error'=> 'Failed create new Permissions']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($permissionId)
    {
        $permissions = $this->permissionRepo->findById($permissionId);
        return $permissions;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permissions = $this->permissionRepo->findById($id);
        return view('acl.permissions.edit')->with(['permissions' => $permissions]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionStoreRequest $request, $id)
    {
        $isUpdated = $this->permissionRepo->update($request->all(), $id);

        if ($isUpdated) {
            return redirect()->back()->with(['success'=> 'Permissions has been updated']);
        }
        return redirect()->back()->with(['error'=> 'Failed updating Permissions']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($permissionId)
    {
        $isDeleted = $this->permissionRepo->delete($permissionId);
        if ($isDeleted) {
            return redirect()->back()->with(['success'=> 'Permissions has been deleted']);
        }
        return redirect()->back()->with(['error'=> 'Failed deleted permissions']);
    }
}

app/Http/Controllers/Acl/RoleController.php
<?php

namespace App\Http\Controllers\Acl;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Acl\Role;
use App\Models\Acl\Permission;
use Carbon\Carbon;
use App\Libraries\Color;
use App\Http\Requests\RoleStoreRequest;
use App\Repositories\RoleRepository;

class RoleController extends Controller {
    
    private $roleRepo;

    public function __construct(RoleRepository $roleRepository)
    {
        $this->roleRepo = $roleRepository;
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index() 
    {
        $roles = Role::paginate( 15 );
        return view('acl.roles.list', ['roles' => $roles ]);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create() 
    {
        return view('acl.roles.new', [
            'colors' => Color::getColors()
        ]);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(RoleStoreRequest $request) 
    {
        $isSaved = $this->roleRepo->save($request);
        if ($isSaved) {
            return redirect()->route('roles.index')->with(['success' => 'Role has been created']);
        }
        return redirect()->back()->with(['error'=> 'Failed created new role']);
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show( $id ) {
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit( $id ) {
        
        // Validate role
        $role = Role::findOrFail($id);
        
        // Source permissions data
        $permissions = Permission::paginate(10);
        // Get all permission by role id
        $rolePermissions = $role->permissions()->get();

        return view('acl.roles.edit', [
            'role' => $role,
            'permissions' => $permissions,
            'totalPermsThisRole' => count($rolePermissions),
            'colors' => Color::getColors()
        ]);
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function showRolePermissions( $id ) {
        
        // Validate role
        $role = Role::findOrFail($id);
        
        // Source data
        $permissions = Permission::paginate(10);
        $rolePermissions = $role->permissions()->get();
        
        // Add extra column for view
        $permissions->map(function ($p){
            $p['status'] = false;        
            return $p;
        });
        
        // Sorting
        foreach ($permissions as $p) {
            if ( count($rolePermissions->where('name', $p->name)) > 0 ) {
                $p['status'] = true;
            }
        }
        
        return view('acl.roles.permissions', [
            'role' => $role,
            'permissions' => $permissions,
            'totalPermsThisRole' => count($rolePermissions)
        ]);
    }
    
    public function removingPermissionFromRole(Request $request, $roleId) {
        
        // Validate role
        $role = Role::findOrFail($roleId);
        
        // Validate permission
        $permission = Permission::findOrFail($request->permission);
        
        
        // Validate if current role have this permission and removing
        if ($role->hasPermissionTo($permission)) {
            if ($role->revokePermissionTo($permission)) {
                
                // Update role parent last update
                $role->updated_at = Carbon::now();
                $role->save(['timestamps' => FALSE]);
                
                return redirect()->back()->with(['success'=> 'Role has been updated']);
            }
        }
        
        return redirect()->route('roles.permissions.edit', $id);
    }
    
    public function addingPermissionToRole(Request $request, $roleId) {
        
        // Validate role
        $role = Role::findOrFail($roleId);
        
        // Validate permission
        $permission = Permission::findOrFail($request->permission);
        
        // Adding permission to role
        if ($role->givePermissionTo($request->permission)) {
            
            // Update role parent last update
            $role->updated_at = Carbon::now();
            $role->save(['timestamps' => FALSE]);
            
            return redirect()->back()->with(['success'=> 'Role has been updated']);
        }
        
        return redirect()->route('roles.permissions.edit', $id);
    }
    
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update( Request $request, $roleId ) {
        
        // Validate form request
        $validatedData = $request->validate([
            'name' => 'required|max:50|min:2',
            'description' => 'required|max:200|min:10',
            'color' => 'required'
        ]);
        
        // Validate role
        $role = Role::findOrFail($roleId);
        
        $update = $role->update([
            'name' => $request->name,
            'description' => $request->description,
            'color' => $request->color
        ]);
        
        if ($update) {
            return redirect()->back()->with(['success'=> 'Role has been updated']);
        }
        
        return redirect()->back()->with(['error'=> 'Failed updating role']);
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy( $id ) {
        //
    }
}

app/Http/Controllers/Acl/UserController.php
<?php

namespace App\Http\Controllers\Acl;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Models\Acl\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Get users except current user login
        $users = User::where('id', '!=', auth()->id())->paginate(10);

        return view('acl.users.list', compact('users'));
    }
    
    public function editingRolesUser($userId) {
        
        // Validate user
        $user = User::findOrFail($userId);
        
        // Get roles user
        $rolesUser = $user->getRoleNames();
        
        // Get roles for option
        $roles = Role::paginate(20);
        
        // Add extra column for view
        $roles->map(function ($r){
            $r['status'] = false;        
            return $r;
        });

        // Sorting
        foreach ($roles as $r) {
            foreach($rolesUser as $ru) {
                if ($r['name'] === $ru) {
                    $r['status'] = true;
                    break;
                }
            }
        }
        
        return view('acl.users.roles', [
            'user' => $user,
            'rolesUser' => $rolesUser,
            'roles' => $roles
        ]);
    }
    
    public function addingRoleToUser(Request $request, $userId) {
        $user = User::findOrFail($userId);
        $role = Role::findOrFail($request->role);
        if ($user->assignRole($role)) {
            return redirect()->back()->with(['success'=> 'Roles user has been updated']);
        }
        return redirect()->back()->with(['error'=> 'Failed updating roles user']);
    }
    
    public function removingRoleFromUser(Request $request, $userId) {
        $user = User::findOrFail($userId);
        $role = Role::findOrFail($request->role);
        if ($user->removeRole($role)) {
            return redirect()->back()->with(['success'=> 'Roles user has been updated']);
        }
        return redirect()->back()->with(['error'=> 'Failed updating roles user']);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/acl/roles/edit.blade.php
@extends('acl.roles.layout')

@section('edit-content')
<div class="tab-pane active" id="role-details">
    <form method="POST" action="{{ route('roles.update', $role->id) }}">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('ID') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control @error('id') is-invalid @enderror" name="id" value="{{ $role->id }}" required />

                @error('id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

            <div class="col-md-6">
                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $role->name }}" required autocomplete="name" />

                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Color') }}</label>
            <div class="col-md-6">
                <select class="form-control @error('color') is-invalid @enderror" name="color" value="{{$role->color}}" id="exampleFormControlSelect1">
                <option></option>
                @foreach($colors as $key => $c)
                <option value="{{$key}}" {{ ( $key === $role->color ) ? 'selected' : '' }} >
                {{ $c }}
                </option>
                @endforeach
                </select>
                @error('color')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group row">
            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

            <div class="col-md-6">
                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="4" required>{{$role->description}}</textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <hr />
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right"></label>

            <div class="col-md-6">
                <button type="submit" class="btn btn-success">Update</button> &nbsp;
                <button type="reset" class="btn btn-outline-dark">Cancel</button>
            </div>
        </div>
    </form>
</div>
<!--</div>-->

@endsection

resources/views/acl/roles/layout.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-sm btn-outline-dark" href="{{ route('roles.index') }}">Back</a>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <h3>Edit Role</h3>
                        <p>This pages contains for editing spesifict roles</p>
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="{{ (request()->is('acl/roles/*/edit')) ? 'nav-link active' : 'nav-link' }}" href="{{ route('roles.edit', $role->id) }}" role="tab" aria-controls="home" aria-selected="true">Details</a>
                            </li>
                            <li class="nav-item">
                                <a class="{{ (request()->is('acl/roles/*/permissions')) ? 'nav-link active' : 'nav-link' }}" href="{{ route('roles.permissions', $role->id) }}" role="tab" aria-controls="profile" aria-selected="false">Permissions ({{$totalPermsThisRole}})</a>
                            </li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        @yield('edit-content')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function validateDelete() {
        if (!confirm('Are you sure want to delete this?')) {
            event.preventDefault();
        }
    }
</script>
@endsection

resources/views/acl/roles/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="text-right">
                        <a role="button" class="btn btn-sm btn-outline-dark" href="{{ route('roles.create') }}">Create New</a>
                    </div>
                </div>
                <div class="card-body">
                    <h3 class="card-tittle">Roles</h3>
                    <p class="card-text">This pages contains list of role</p> <hr/>
                    @foreach($roles->chunk(3) as $chunk)
                    <div class="row">
                        @foreach($chunk as $role)
                        <div class="col-md-4 col-sm-12 mb-1">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ $role->name }} <span class="text-danger">*</span></h5> 
                                <p class="card-text">{{ $role->description }}</p>
                                <a href="{{ route( 'roles.edit',  $role->id) }}" class="btn btn-info btn-sm text-white" role="button">View Details</a>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Last updated {{ Carbon\Carbon::parse($role->updated_at)->diffForHumans()}} </small>
                            </div>
                        </div>
                        </div>
                        @endforeach
                    </div>
                    <br>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/acl/roles/new.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-sm btn-outline-dark" href="{{ route('roles.index') }}">Back</a>
                </div>
                <div class="card-body">
                    <h3 class="card-tittle">Create Role</h3>
                    <p class="card-text">Pages for creating a new role</p>
                    <hr />
                    <form method="POST" action="{{ route('roles.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" />
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Color') }}</label>
                            <div class="col-md-6">
                                <select class="form-control @error('color') is-invalid @enderror" name="color" value="{{ old('color') }}" id="exampleFormControlSelect1">
                                    <option></option>
                                    @foreach($colors as $key => $c)
                                    <option value="{{$key}}" {{ ( $key === old('color') ) ? 'selected' : '' }}>
                                        {{ $c }}
                                    </option>
                                    @endforeach
                                </select>
                                @error('color')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>
                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="4" required>{{ old('description')}}</textarea>
                                @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <hr />
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right"></label>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success">Create</button> &nbsp;
                                <button type="reset" class="btn btn-outline-dark">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection